# [Analyzing an Internal Speech Dataset ](https://www.nature.com/articles/s41597-022-01147-2#Sec2)

In [1]:
from dotenv import load_dotenv 
import os
from glob import glob
import mne
import numpy as np
import pickle
import torch
load_dotenv()
root_dir = os.getenv("ROOT_DIR")

In [2]:
root_dir

'/media/linux-pc/Stargate/inner-speech/ds003626-download/'

In [3]:
all_file_l = sorted(glob(os.path.join(root_dir, "**", "*.*"), recursive=True))

In [4]:
X_data_l_eeg = sorted(glob(os.path.join(root_dir, "derivatives", "**", "**", "*.eeg-epo.fif"), recursive=True))
y_data_l_eeg = sorted(glob(os.path.join(root_dir, "derivatives", "**", "**", "*.events.dat"), recursive=True))

In [5]:
all_file_l

['/media/linux-pc/Stargate/inner-speech/ds003626-download/dataset_description.json',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_baseline-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_eeg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_events.dat',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_exg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_report.pkl',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_baseline-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_eeg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_events.dat',
 '/media/lin

In [6]:
bdf_file_l = sorted(glob(os.path.join(root_dir, "**", "*.bdf"), recursive=True))

In [7]:
bdf_file_l[:5]

['/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-01/ses-01/eeg/sub-01_ses-01_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-01/ses-02/eeg/sub-01_ses-02_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-01/ses-03/eeg/sub-01_ses-03_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-02/ses-01/eeg/sub-02_ses-01_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-02/ses-02/eeg/sub-02_ses-02_task-innerspeech_eeg.bdf']

In [8]:
bdf_path = bdf_file_l[0]

In [9]:
raw = mne.io.read_raw_bdf(bdf_path, preload=True)

Extracting EDF parameters from /media/linux-pc/Stargate/inner-speech/ds003626-download/sub-01/ses-01/eeg/sub-01_ses-01_task-innerspeech_eeg.bdf...
BDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1875967  =      0.000 ...  1831.999 secs...


In [13]:
print(raw.info)

<Info | 7 non-empty values
 bads: []
 ch_names: A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, ...
 chs: 136 EEG, 1 STIM
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 208.0 Hz
 meas_date: 2019-08-20 10:57:41 UTC
 nchan: 137
 projs: []
 sfreq: 1024.0 Hz
>


In [14]:
events, event_id = mne.events_from_annotations(raw)
print("Event labels and IDs:", event_id)

Event labels and IDs: {}


In [15]:
all_file_l[1]

'/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_baseline-epo.fif'

In [16]:
eeg_epochs_path = all_file_l[1]

In [17]:
epochs = mne.read_epochs(eeg_epochs_path, preload=True)

Reading /media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_baseline-epo.fif ...
Isotrak not found
    Found the data of interest:
        t =       0.00 ...   15000.00 ms
        0 CTF compensation matrices available
Not setting metadata
Not setting metadata
1 matching events found
No baseline correction applied
0 projection items activated


In [18]:
print(epochs)

<EpochsFIF |  1 events (all good), 0 - 15 sec, baseline off, ~4.2 MB, data loaded,
 'Baseline': 1>


In [19]:
epochs.event_id

{'Baseline': 13}

In [20]:
all_file_l

['/media/linux-pc/Stargate/inner-speech/ds003626-download/dataset_description.json',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_baseline-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_eeg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_events.dat',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_exg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_report.pkl',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_baseline-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_eeg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_events.dat',
 '/media/lin

In [21]:
all_file_l[7]

'/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_eeg-epo.fif'

In [22]:
eeg_epochs_path = all_file_l[7]

In [23]:
epochs = mne.read_epochs(eeg_epochs_path, preload=True)

Reading /media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_eeg-epo.fif ...
Isotrak not found
    Found the data of interest:
        t =    -500.00 ...    4000.00 ms
        0 CTF compensation matrices available
Not setting metadata
Not setting metadata
200 matching events found
No baseline correction applied
0 projection items activated


In [24]:
print(epochs)

<EpochsFIF |  200 events (all good), -0.5 - 4 sec, baseline off, ~225.3 MB, data loaded,
 'Abajo': 50
 'Arriba': 50
 'Derecha': 50
 'Izquierda': 50>


In [25]:
epochs.event_id

{'Arriba': 31, 'Abajo': 32, 'Derecha': 33, 'Izquierda': 34}

In [26]:
epochs.events

array([[  42418,       0,      31],
       [  49056,       0,      33],
       [  55763,       0,      31],
       [  62146,       0,      34],
       [  68836,       0,      34],
       [  75424,       0,      34],
       [  81806,       0,      33],
       [  88462,       0,      32],
       [  94930,       0,      32],
       [ 101364,       0,      31],
       [ 107849,       0,      31],
       [ 114300,       0,      32],
       [ 120786,       0,      33],
       [ 127185,       0,      32],
       [ 133892,       0,      34],
       [ 140395,       0,      31],
       [ 147033,       0,      32],
       [ 153774,       0,      33],
       [ 160396,       0,      32],
       [ 167035,       0,      33],
       [ 173622,       0,      34],
       [ 180056,       0,      34],
       [ 186678,       0,      34],
       [ 193505,       0,      31],
       [ 200297,       0,      33],
       [ 206782,       0,      33],
       [ 213250,       0,      32],
       [ 219906,       0,   

In [27]:
epochs = mne.read_epochs(eeg_epochs_path, preload=True)
event_map = {v: k for k, v in epochs.event_id.items()}

Reading /media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_eeg-epo.fif ...
Isotrak not found
    Found the data of interest:
        t =    -500.00 ...    4000.00 ms
        0 CTF compensation matrices available
Not setting metadata
Not setting metadata
200 matching events found
No baseline correction applied
0 projection items activated


In [28]:
labels = [event_map[event[-1]] for event in epochs.events]

In [29]:
labels.__len__()

200

In [30]:
[label for label in labels if label == "Arriba"].__len__()

50

In [31]:
X = epochs.get_data()
y = labels

In [32]:
X.shape

(200, 128, 1153)

In [33]:
X.shape

(200, 128, 1153)

In [34]:
y

['Arriba',
 'Derecha',
 'Arriba',
 'Izquierda',
 'Izquierda',
 'Izquierda',
 'Derecha',
 'Abajo',
 'Abajo',
 'Arriba',
 'Arriba',
 'Abajo',
 'Derecha',
 'Abajo',
 'Izquierda',
 'Arriba',
 'Abajo',
 'Derecha',
 'Abajo',
 'Derecha',
 'Izquierda',
 'Izquierda',
 'Izquierda',
 'Arriba',
 'Derecha',
 'Derecha',
 'Abajo',
 'Derecha',
 'Izquierda',
 'Arriba',
 'Arriba',
 'Abajo',
 'Derecha',
 'Arriba',
 'Abajo',
 'Arriba',
 'Derecha',
 'Abajo',
 'Izquierda',
 'Izquierda',
 'Abajo',
 'Abajo',
 'Derecha',
 'Derecha',
 'Izquierda',
 'Arriba',
 'Arriba',
 'Derecha',
 'Abajo',
 'Abajo',
 'Izquierda',
 'Abajo',
 'Derecha',
 'Arriba',
 'Izquierda',
 'Arriba',
 'Arriba',
 'Arriba',
 'Derecha',
 'Abajo',
 'Abajo',
 'Abajo',
 'Izquierda',
 'Derecha',
 'Abajo',
 'Derecha',
 'Arriba',
 'Abajo',
 'Derecha',
 'Izquierda',
 'Derecha',
 'Izquierda',
 'Izquierda',
 'Arriba',
 'Izquierda',
 'Izquierda',
 'Derecha',
 'Izquierda',
 'Arriba',
 'Arriba',
 'Abajo',
 'Abajo',
 'Izquierda',
 'Abajo',
 'Arriba',
 'Izq

### Subject 1

In [35]:
subject_1 = sorted(glob(os.path.join(root_dir, "derivatives", "sub-01", "**", "*.*"), recursive=True))

In [36]:
subject_1

['/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_baseline-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_eeg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_events.dat',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_exg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_report.pkl',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_baseline-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_eeg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_events.dat',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02

In [37]:
subject_1.__len__()

15

In [38]:
subject_1[:5]

['/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_baseline-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_eeg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_events.dat',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_exg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_report.pkl']

In [39]:
subject_1[:5]

['/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_baseline-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_eeg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_events.dat',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_exg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_report.pkl']

In [40]:
# Load EEG epochs
epochs_eeg = mne.read_epochs(subject_1[1], preload=True)

Reading /media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_eeg-epo.fif ...
Isotrak not found
    Found the data of interest:
        t =    -500.00 ...    4000.00 ms
        0 CTF compensation matrices available
Not setting metadata
Not setting metadata
200 matching events found
No baseline correction applied
0 projection items activated


In [41]:
epochs_eeg

<EpochsFIF |  200 events (all good), -0.5 - 4 sec, baseline off, ~225.3 MB, data loaded,
 'Abajo': 50
 'Arriba': 50
 'Derecha': 50
 'Izquierda': 50>

In [42]:
epochs_eeg.get_data().shape

(200, 128, 1153)

In [43]:
# y-labels: 

events = np.load(subject_1[2], allow_pickle=True)
print(events)

[[  39869       3       0       1]
 [  46491       0       0       1]
 [  53010       3       0       1]
 [  59649       3       0       1]
 [  66270       2       0       1]
 [  73063       1       0       1]
 [  79838       3       0       1]
 [  86528       1       0       1]
 [  93064       3       0       1]
 [  99823       1       0       1]
 [ 106461       0       0       1]
 [ 113015       0       0       1]
 [ 119824       3       0       1]
 [ 126651       2       0       1]
 [ 133289       1       0       1]
 [ 139996       0       0       1]
 [ 146669       0       0       1]
 [ 153154       3       0       1]
 [ 159691       1       0       1]
 [ 166295       3       0       1]
 [ 172815       1       0       1]
 [ 179641       2       0       1]
 [ 186109       1       0       1]
 [ 192612       0       0       1]
 [ 199080       2       0       1]
 [ 205582       2       0       1]
 [ 212169       1       0       1]
 [ 218723       0       0       1]
 [ 225583       2   

In [44]:
subject_1

['/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_baseline-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_eeg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_events.dat',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_exg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_report.pkl',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_baseline-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_eeg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_events.dat',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02

In [45]:
events[0]

array([39869,     3,     0,     1])

In [46]:
# Sample | Trials Class [0, 1, 2, 3 : "Arriba", "Abajo", "Derecha", "Izquierda"] | Trials Condition : Inner Speech == 1 | Trails Session : Use 1 & 2 for all participants

In [47]:
subject_1[3]

'/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_exg-epo.fif'

In [48]:
subject_1[4]

'/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_report.pkl'

In [49]:
with open(subject_1[4], 'rb') as f:
    subject_data = pickle.load(f)
print(type(subject_data))

<class 'dict'>


In [50]:
subject_data

{'Age': 56,
 'Gender': 'F',
 'Recording_time': 1832,
 'Ans_R': 43,
 'Ans_W': 2,
 'EMG_trials': array([ 44.,  55.,  56.,  59., 148., 155.]),
 'Power_EXG7': array([1.66555993e-09, 1.78973692e-10, 3.09067948e-11, 4.65290829e-10,
        3.16289043e-09, 1.00091801e-09]),
 'Power_EXG8': array([1.40977914e-09, 3.52279347e-10, 2.23067212e-10, 5.91289131e-10,
        6.02205634e-09, 6.62926101e-10]),
 'Baseline_EXG7_mean': 2.1510271959948184e-10,
 'Baseline_EXG8_mean': 6.148708634155476e-11,
 'Baseline_EXG7_std': 1.5097728063882982e-10,
 'Baseline_EXG8_std': 4.116691114385579e-11}

# Acquiring EEG data for all 10 subjects for X

In [51]:
data_l_epochs = sorted(glob(os.path.join(root_dir, "derivatives", "sub-*", "ses-*", "sub-*_ses-*_eeg-epo.fif"), recursive=True))
data_l_epochs = [f for f in X_data_l_eeg if "ses-03" not in f]
epochs = mne.read_epochs(data_l_epochs[0], preload=True)
X = epochs.get_data()
### Extacting Labels
event_map = {v: k for k, v in epochs.event_id.items()}
y = [event_map[event[-1]] for event in epochs.events]

IndexError: list index out of range

In [52]:
import os
from glob import glob
import mne
import numpy as np

# Path to your dataset
root_dir = "/media/linux-pc/Stargate/inner-speech/ds003626-download"

# 1. Find all .fif files except those in ses-03
data_l_epochs = sorted(glob(os.path.join(root_dir, "derivatives", "sub-*", "ses-*", "sub-*_ses-*_eeg-epo.fif"), recursive=True))
data_l_epochs = [f for f in data_l_epochs if "ses-03" not in f]

# 2. Initialize containers for all X and y
X_all = []
y_all = []

# 3. Loop over each file, load epochs, extract data and labels
for path in data_l_epochs:
    epochs = mne.read_epochs(path, preload=True)
    X = epochs.get_data()  # shape: (n_epochs, n_channels, n_samples)

    # Build label map
    event_map = {v: k for k, v in epochs.event_id.items()}
    y = [event_map[event[-1]] for event in epochs.events]  # match labels by last event column

    # Append to global list
    X_all.append(X)
    y_all.extend(y)

# 4. Stack X into one NumPy array and y into one list (or array)
X_all = np.concatenate(X_all, axis=0)
y_all = np.array(y_all)

# 5. Report
print(f"Total epochs: {X_all.shape[0]}")
print(f"Shape of X: {X_all.shape}")  # (total_trials, n_channels, n_samples)
print(f"Number of labels: {len(y_all)}")
print(f"Example labels: {y_all[:10]}")


Reading /media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_eeg-epo.fif ...
Isotrak not found
    Found the data of interest:
        t =    -500.00 ...    4000.00 ms
        0 CTF compensation matrices available
Not setting metadata
Not setting metadata
200 matching events found
No baseline correction applied
0 projection items activated
Reading /media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_eeg-epo.fif ...
Isotrak not found
    Found the data of interest:
        t =    -500.00 ...    4000.00 ms
        0 CTF compensation matrices available
Not setting metadata
Not setting metadata
200 matching events found
No baseline correction applied
0 projection items activated
Reading /media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-02/ses-01/sub-02_ses-01_eeg-epo.fif ...
Isotrak not found
    Found the data of interest:
        t =    -500.00 ...    4000.00 ms
        0 CTF compe

: 