# Imports, Settings, & Functions

In [1]:
from dotenv import load_dotenv 
import os
from glob import glob
import mne
import numpy as np
import pickle
import torch
load_dotenv()
root_dir = os.getenv("ROOT_DIR")

In [2]:
root_dir

'/media/linux-pc/Stargate/inner-speech/ds003626-download/'

In [3]:
all_file_l = sorted(glob(os.path.join(root_dir, "**", "*.*"), recursive=True))

In [4]:
all_file_l

['/media/linux-pc/Stargate/inner-speech/ds003626-download/dataset_description.json',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_baseline-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_eeg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_events.dat',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_exg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-01/sub-01_ses-01_report.pkl',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_baseline-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_eeg-epo.fif',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/derivatives/sub-01/ses-02/sub-01_ses-02_events.dat',
 '/media/lin

In [5]:
bdf_file_l = sorted(glob(os.path.join(root_dir, "**", "*.bdf"), recursive=True))

In [6]:
bdf_file_l[:5]

['/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-01/ses-01/eeg/sub-01_ses-01_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-01/ses-02/eeg/sub-01_ses-02_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-01/ses-03/eeg/sub-01_ses-03_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-02/ses-01/eeg/sub-02_ses-01_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-02/ses-02/eeg/sub-02_ses-02_task-innerspeech_eeg.bdf']

In [24]:
bdf_file_l

['/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-01/ses-01/eeg/sub-01_ses-01_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-01/ses-02/eeg/sub-01_ses-02_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-01/ses-03/eeg/sub-01_ses-03_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-02/ses-01/eeg/sub-02_ses-01_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-02/ses-02/eeg/sub-02_ses-02_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-02/ses-03/eeg/sub-02_ses-03_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-03/ses-01/eeg/sub-03_ses-01_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-03/ses-02/eeg/sub-03_ses-02_task-innerspeech_eeg.bdf',
 '/media/linux-pc/Stargate/inner-speech/ds003626-download/sub-03

In [25]:
bdf_file_path = bdf_file_l[0]

In [26]:
raw_bdf_data = mne.io.read_raw_bdf(bdf_file_path, preload=True)

Extracting EDF parameters from /media/linux-pc/Stargate/inner-speech/ds003626-download/sub-01/ses-01/eeg/sub-01_ses-01_task-innerspeech_eeg.bdf...
BDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1875967  =      0.000 ...  1831.999 secs...


In [27]:
raw_bdf_data.get_data().shape

(137, 1875968)

In [28]:
raw_bdf_data

<RawEDF | sub-01_ses-01_task-innerspeech_eeg.bdf, 137 x 1875968 (1832.0 s), ~1.91 GB, data loaded>

In [29]:
raw_bdf_data.info

<Info | 7 non-empty values
 bads: []
 ch_names: A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, ...
 chs: 136 EEG, 1 STIM
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 208.0 Hz
 meas_date: 2019-08-20 10:57:41 UTC
 nchan: 137
 projs: []
 sfreq: 1024.0 Hz
>

In [30]:
raw_bdf_data.ch_names


['A1',
 'A2',
 'A3',
 'A4',
 'A5',
 'A6',
 'A7',
 'A8',
 'A9',
 'A10',
 'A11',
 'A12',
 'A13',
 'A14',
 'A15',
 'A16',
 'A17',
 'A18',
 'A19',
 'A20',
 'A21',
 'A22',
 'A23',
 'A24',
 'A25',
 'A26',
 'A27',
 'A28',
 'A29',
 'A30',
 'A31',
 'A32',
 'B1',
 'B2',
 'B3',
 'B4',
 'B5',
 'B6',
 'B7',
 'B8',
 'B9',
 'B10',
 'B11',
 'B12',
 'B13',
 'B14',
 'B15',
 'B16',
 'B17',
 'B18',
 'B19',
 'B20',
 'B21',
 'B22',
 'B23',
 'B24',
 'B25',
 'B26',
 'B27',
 'B28',
 'B29',
 'B30',
 'B31',
 'B32',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'C15',
 'C16',
 'C17',
 'C18',
 'C19',
 'C20',
 'C21',
 'C22',
 'C23',
 'C24',
 'C25',
 'C26',
 'C27',
 'C28',
 'C29',
 'C30',
 'C31',
 'C32',
 'D1',
 'D2',
 'D3',
 'D4',
 'D5',
 'D6',
 'D7',
 'D8',
 'D9',
 'D10',
 'D11',
 'D12',
 'D13',
 'D14',
 'D15',
 'D16',
 'D17',
 'D18',
 'D19',
 'D20',
 'D21',
 'D22',
 'D23',
 'D24',
 'D25',
 'D26',
 'D27',
 'D28',
 'D29',
 'D30',
 'D31',
 'D32',
 'EXG1',
 'E

In [31]:
raw_bdf_data.get_data().shape

(137, 1875968)

In [32]:
type(raw_bdf_data)

mne.io.edf.edf.RawEDF

In [33]:
raw_bdf_data.info['sfreq']

1024.0

In [34]:
raw_bdf_data.n_times / raw_bdf_data.info['sfreq']

1832.0

In [35]:
sfreq = int(raw_bdf_data.info['sfreq'])
total_seconds = int(raw_bdf_data.n_times / sfreq)
total_seconds

1832

In [36]:
sfreq

1024

In [37]:
raw_bdf_data.n_times

1875968

In [38]:
raw_bdf_data[:, 1874944:1875968][0]

array([[ 0.00232595,  0.00232595,  0.00232564, ...,  0.00231642,
         0.00231607,  0.00231573],
       [ 0.00446126,  0.00446094,  0.00445979, ...,  0.00445266,
         0.00445282,  0.00445232],
       [ 0.00409498,  0.00409445,  0.00409504, ...,  0.00408738,
         0.0040881 ,  0.00408835],
       ...,
       [-0.00747322, -0.00741863, -0.00736685, ..., -0.00667875,
        -0.0066391 , -0.00663941],
       [-0.00568057, -0.00563319, -0.00559363, ..., -0.00493704,
        -0.00491004, -0.00487285],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
# ALL RAW data for 1024 samples each second for all channels
for second in range(0, total_seconds):
    index_start = sfreq * second
    index_stop = sfreq * (second+1)
    print(raw_bdf_data[:, index_start:index_stop])

(array([[ 3.58663400e-03,  3.58547775e-03,  3.58235275e-03, ...,
         3.56550904e-03,  3.56613403e-03,  3.56729028e-03],
       [ 4.54881972e-03,  4.54950722e-03,  4.54616347e-03, ...,
         4.53153850e-03,  4.53200725e-03,  4.53110100e-03],
       [ 3.63310266e-03,  3.63122766e-03,  3.62841517e-03, ...,
         3.61585269e-03,  3.61666519e-03,  3.61732144e-03],
       ...,
       [-7.40175195e-03, -7.38153324e-03, -7.36643951e-03, ...,
        -7.24165850e-03, -7.22350228e-03, -7.20762731e-03],
       [-7.13815869e-03, -7.14775242e-03, -7.15534615e-03, ...,
        -7.15250241e-03, -7.16125239e-03, -7.15843990e-03],
       [ 6.55360000e+04,  6.55360000e+04,  6.55360000e+04, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]]), array([0.00000000e+00, 9.76562500e-04, 1.95312500e-03, ...,
       9.97070312e-01, 9.98046875e-01, 9.99023438e-01]))
(array([[ 0.00356851,  0.00356682,  0.00356601, ...,  0.00355807,
         0.0035577 ,  0.0035561 ],
       [ 0.00453235,  0

# Examining Events

In [48]:
events, event_id = mne.events_from_annotations(raw_bdf_data)

In [65]:
raw_bdf_data.info["ch_names"]

['A1',
 'A2',
 'A3',
 'A4',
 'A5',
 'A6',
 'A7',
 'A8',
 'A9',
 'A10',
 'A11',
 'A12',
 'A13',
 'A14',
 'A15',
 'A16',
 'A17',
 'A18',
 'A19',
 'A20',
 'A21',
 'A22',
 'A23',
 'A24',
 'A25',
 'A26',
 'A27',
 'A28',
 'A29',
 'A30',
 'A31',
 'A32',
 'B1',
 'B2',
 'B3',
 'B4',
 'B5',
 'B6',
 'B7',
 'B8',
 'B9',
 'B10',
 'B11',
 'B12',
 'B13',
 'B14',
 'B15',
 'B16',
 'B17',
 'B18',
 'B19',
 'B20',
 'B21',
 'B22',
 'B23',
 'B24',
 'B25',
 'B26',
 'B27',
 'B28',
 'B29',
 'B30',
 'B31',
 'B32',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'C15',
 'C16',
 'C17',
 'C18',
 'C19',
 'C20',
 'C21',
 'C22',
 'C23',
 'C24',
 'C25',
 'C26',
 'C27',
 'C28',
 'C29',
 'C30',
 'C31',
 'C32',
 'D1',
 'D2',
 'D3',
 'D4',
 'D5',
 'D6',
 'D7',
 'D8',
 'D9',
 'D10',
 'D11',
 'D12',
 'D13',
 'D14',
 'D15',
 'D16',
 'D17',
 'D18',
 'D19',
 'D20',
 'D21',
 'D22',
 'D23',
 'D24',
 'D25',
 'D26',
 'D27',
 'D28',
 'D29',
 'D30',
 'D31',
 'D32',
 'EXG1',
 'E

In [66]:
events = mne.find_events(raw_bdf_data, stim_channel='Status')

Trigger channel has a non-zero initial value of 65536 (consider using initial_event=True to detect this event)


Removing orphaned offset at the beginning of the file.
1112 events found
Event IDs: [11 12 13 14 15 16 17 21 22 23 31 32 33 34 42 44 45 46 51 61 62 63 64]


In [68]:
events.shape

(1112, 3)

In [ ]:
events

array([[   6283,       0,      11],
       [  16591,       0,      13],
       [  31976,       0,      14],
       ...,
       [1829105,       0,      46],
       [1829126,       0,      16],
       [1829156,       0,      12]])

: 

In [55]:
raw_bdf_data.get_data()

array([[ 3.58663400e-03,  3.58547775e-03,  3.58235275e-03, ...,
         2.31641759e-03,  2.31607384e-03,  2.31573010e-03],
       [ 4.54881972e-03,  4.54950722e-03,  4.54616347e-03, ...,
         4.45266365e-03,  4.45281990e-03,  4.45231990e-03],
       [ 3.63310266e-03,  3.63122766e-03,  3.62841517e-03, ...,
         4.08738307e-03,  4.08810182e-03,  4.08835182e-03],
       ...,
       [-7.40175195e-03, -7.38153324e-03, -7.36643951e-03, ...,
        -6.67875329e-03, -6.63909711e-03, -6.63940961e-03],
       [-7.13815869e-03, -7.14775242e-03, -7.15534615e-03, ...,
        -4.93703775e-03, -4.91003780e-03, -4.87285037e-03],
       [ 6.55360000e+04,  6.55360000e+04,  6.55360000e+04, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [54]:
raw_bdf_data.info["ch_names"]

['A1',
 'A2',
 'A3',
 'A4',
 'A5',
 'A6',
 'A7',
 'A8',
 'A9',
 'A10',
 'A11',
 'A12',
 'A13',
 'A14',
 'A15',
 'A16',
 'A17',
 'A18',
 'A19',
 'A20',
 'A21',
 'A22',
 'A23',
 'A24',
 'A25',
 'A26',
 'A27',
 'A28',
 'A29',
 'A30',
 'A31',
 'A32',
 'B1',
 'B2',
 'B3',
 'B4',
 'B5',
 'B6',
 'B7',
 'B8',
 'B9',
 'B10',
 'B11',
 'B12',
 'B13',
 'B14',
 'B15',
 'B16',
 'B17',
 'B18',
 'B19',
 'B20',
 'B21',
 'B22',
 'B23',
 'B24',
 'B25',
 'B26',
 'B27',
 'B28',
 'B29',
 'B30',
 'B31',
 'B32',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'C15',
 'C16',
 'C17',
 'C18',
 'C19',
 'C20',
 'C21',
 'C22',
 'C23',
 'C24',
 'C25',
 'C26',
 'C27',
 'C28',
 'C29',
 'C30',
 'C31',
 'C32',
 'D1',
 'D2',
 'D3',
 'D4',
 'D5',
 'D6',
 'D7',
 'D8',
 'D9',
 'D10',
 'D11',
 'D12',
 'D13',
 'D14',
 'D15',
 'D16',
 'D17',
 'D18',
 'D19',
 'D20',
 'D21',
 'D22',
 'D23',
 'D24',
 'D25',
 'D26',
 'D27',
 'D28',
 'D29',
 'D30',
 'D31',
 'D32',
 'EXG1',
 'E